#spring settings
spring:
  boot:
    admin:
      client:
        url: http://localhost:8525
        instance:
          prefer-ip: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/maxibetdb?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&stringtype=unspecified
    username: maxibet
    password: globalTLLC09
  rabbitmq:
    addresses: 192.168.159.1:5672
    username: fengy
    password: 123456
    virtual-host: /local